-- [ Universal AutoExec ] --
-- Generated by Antigravity
-- Combines: ahhfrro.txt, salegrosfdp.lua, salenegro.lua, slayzz.lua
-- Properties: Desync Auto-On, No GUI, Persistent

-- [[ 1. Desync Script (ahhfrro.txt - Modified) ]] --
task.spawn(function()
    local cloneref = cloneref or function(o) return o end
    local getgenv = getgenv or function() return _G end
    local function GetSafeService(name) return cloneref(game:GetService(name)) end

    local Players = GetSafeService("Players")
    local TeleportService = GetSafeService("TeleportService")
    local HttpService = GetSafeService("HttpService")
    local LocalPlayer = Players.LocalPlayer

    -- [CONFIG / PERSISTENCE]
    local ConfigFile = "desync_state.json"
    local State = { IsOn = false }

    local function SaveState()
        if writefile then
            pcall(function() writefile(ConfigFile, HttpService:JSONEncode(State)) end)
        end
    end

    local function LoadState()
        if readfile and isfile and isfile(ConfigFile) then
            pcall(function()
                local decoded = HttpService:JSONDecode(readfile(ConfigFile))
                if decoded then State = decoded end
            end)
        end
    end
    LoadState()

    -- [DESYNC LOGIC]
    local setfflag = getgenv().setfflag or function(...) end

    local DesyncFlags = {
        GameNetPVHeaderRotationalVelocityZeroCutoffExponent = -5000,
        LargeReplicatorWrite5 = true,
        LargeReplicatorEnabled9 = true,
        AngularVelociryLimit = 360,
        TimestepArbiterVelocityCriteriaThresholdTwoDt = 2147483646,
        S2PhysicsSenderRate = 15000,
        DisableDPIScale = true,
        MaxDataPacketPerSend = 2147483647,
        PhysicsSenderMaxBandwidthBps = 20000,
        TimestepArbiterHumanoidLinearVelThreshold = 21,
        MaxMissedWorldStepsRemembered = -2147483648,
        PlayerHumanoidPropertyUpdateRestrict = true,
        SimDefaultHumanoidTimestepMultiplier = 0,
        StreamJobNOUVolumeLengthCap = 2147483647,
        DebugSendDistInSteps = -2147483648,
        GameNetDontSendRedundantNumTimes = 1,
        CheckPVLinearVelocityIntegrateVsDeltaPositionThresholdPercent = 1,
        CheckPVDifferencesForInterpolationMinVelThresholdStudsPerSecHundredth = 1,
        LargeReplicatorSerializeRead3 = true,
        ReplicationFocusNouExtentsSizeCutoffForPauseStuds = 2147483647,
        CheckPVCachedVelThresholdPercent = 10,
        CheckPVDifferencesForInterpolationMinRotVelThresholdRadsPerSecHundredth = 1,
        GameNetDontSendRedundantDeltaPositionMillionth = 1,
        InterpolationFrameVelocityThresholdMillionth = 5,
        StreamJobNOUVolumeCap = 2147483647,
        InterpolationFrameRotVelocityThresholdMillionth = 5,
        CheckPVCachedRotVelThresholdPercent = 10,
        WorldStepMax = 30,
        InterpolationFramePositionThresholdMillionth = 5,
        TimestepArbiterHumanoidTurningVelThreshold = 1,
        SimOwnedNOUCountThresholdMillionth = 2147483647,
        GameNetPVHeaderLinearVelocityZeroCutoffExponent = -5000,
        NextGenReplicatorEnabledWrite4 = true,
        TimestepArbiterOmegaThou = 1073741823,
        MaxAcceptableUpdateDelay = 1,
        LargeReplicatorSerializeWrite4 = true
    }

    local function applyFlags(flagTable)
        for name, value in pairs(flagTable) do
            pcall(function()
                setfflag(tostring(name), tostring(value))
            end)
        end
    end

    local function fastRejoin()
        task.wait(0.15) -- temps minimum pour écrire le flag
        TeleportService:TeleportToPlaceInstance(
            game.PlaceId,
            game.JobId,
            LocalPlayer
        )
    end

    -- [AUTO EXECUTION LOGIC]
    -- If not ON, turn ON, Save, Apply, and Rejoin.
    -- If ON, just Apply.
    
    if not State.IsOn then
        State.IsOn = true
        SaveState()
        applyFlags(DesyncFlags)
        print("[Universal AutoExec] Desync Enabling -> Rejoining...")
        fastRejoin()
    else
        applyFlags(DesyncFlags)
        print("[Universal AutoExec] Desync Active")
    end
end)

-- [[ 2. Anti-Gray Screen (salegrosfdp.lua) ]] --
task.spawn(function()
    -- [[ Focused Anti-Gray Screen ]] --
    -- Specifically designed to detect and remove the "Gray Screen" overlay

    local GuiService = game:GetService("GuiService")
    local CoreGui = game:GetService("CoreGui")

    -- Function to force-remove the error overlay (Gray Screen)
    local function RemoveGrayScreen()
        pcall(function()
            -- Direct call to clear errors which causes the gray screen
            GuiService:ClearError()
        end)
        
        -- Additionally, search for and disable any persistent error prompts in CoreGui
        pcall(function()
            local promptGui = CoreGui:FindFirstChild("RobloxPromptGui")
            if promptGui then
                local promptFrame = promptGui:FindFirstChild("promptBorder", true)
                if promptFrame then
                    promptFrame.Parent.Visible = false
                end
            end
        end)
    end

    -- Continuous loop to ensure the gray screen is suppressed
    task.spawn(function()
        while task.wait(0.2) do -- Fast check to remove it instantly
            RemoveGrayScreen()
            
            -- Special check: If we are stuck in a state where the screen is dimmed
            -- but no error is visible, we can try to "nudge" the UI
            pcall(function()
                if GuiService:GetErrorMessage() ~= "" then
                    RemoveGrayScreen()
                end
            end)
        end
    end)

    -- Anti-Gray Screen on Join/Teleport
    game:GetService("TeleportService").TeleportInitFailed:Connect(function()
        task.wait(0.1)
        RemoveGrayScreen()
    end)

    -- Detect when prompts are added and kill them
    CoreGui.ChildAdded:Connect(function(child)
        if child.Name == "RobloxPromptGui" then
            RemoveGrayScreen()
        end
    end)

    print("[Universal AutoExec] Anti-Gray Screen Active")
end)

-- [[ 3. Loader (salenegro.lua) ]] --
task.spawn(function()
   

-- [[ 4. Chilli (slayzz.lua) ]] --
task.spawn(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/tienkhanh1/spicy/main/Chilli.lua"))()
end)
